hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

local_rank: 0
world_size: 1

run: 0
dataset: TEXT8
data_dir: ./data/datasets/
model_dir: ./models/
log_dir: ./logs/

batch_size: 180
n_epochs: 14001
lr: 5e-4

seqlen: 250

mask:
  strategy: none
  order: random
  mixture: False
  normalize_cardinality: False

mode: train
arch: Transformer

loadpath:

defaults:
  - override hydra/job_logging: custom